/* Europe 2026 — the 23 days. Attaches to TRIP from data.js. */

TRIP.days = [
  {
    img: "slc",
    n: 1, iso: "2026-09-17", date: "Thu 17 Sep", city: "Salt Lake City", country: "USA",
    kind: "travel", title: "Fly out",
    summary: "Overnight to Paris, then on to Rome tomorrow. 14h 55m door to door with one stop.",
    high: 77, low: 52, rain: 0.18,
    timeline: [
      { t: "3:30 PM", what: "DL 220 departs SLC", detail: "Salt Lake City → Paris CDG · A330-900neo · 10h 00m · Brandon seat 49H" },
    ],
    notes: [
      "Two free checked bags each, 23 kg. Boarding passes in the Fly Delta app — download them before you leave the house.",
    ],
    checklist: ["Passports", "Both phones fully charged", "Chargers + EU adapters", "Ticket barcodes saved offline", "Meds and anything you need in the cabin"],
  },
  {
    img: "rome-pantheon",
    n: 2, iso: "2026-09-18", date: "Fri 18 Sep", city: "Rome", country: "Italy",
    kind: "travel", title: "Paris → Rome",
    summary: "Arrive 2:25 PM. Nothing booked after that — keep it that way after an overnight flight.",
    high: 81, low: 63, rain: 0.27,
    timeline: [
      { t: "9:30 AM", what: "Land at Paris CDG", detail: "Terminal 2E. Passport control here — this is your entry into Schengen." },
      { t: "12:15 PM", what: "DL 8299 departs", detail: "Paris CDG (2F) → Rome Fiumicino · A320 · 2h 10m · Brandon seat 16F. Allow for the 2E→2F walk." },
      { t: "2:25 PM", what: "Land at Fiumicino", detail: "Terminal 1. Domestic-style arrival — you already cleared Schengen at CDG. ~40 min for bags." },
      { t: "~3:15 PM", what: "Car to the apartment", detail: "Rome runs a REGULATED FLAT FARE from FCO to anywhere inside the Aurelian Walls, and Via dei Cappellari qualifies. Use the official white-taxi rank outside arrivals and ask for the tariffa fissa to the centro storico. Ignore anyone touting inside the terminal. ~50 min." },
      { t: "~4:15 PM", what: "Check in", detail: "Via dei Cappellari 4. Check-in from 3:00 PM. Narrow ZTL lane — expect a short walk from where the car can stop." },
    ],
    notes: ["Nothing booked tonight. That is deliberate."],
  },
  {
    img: "rome-trevi",
    n: 3, iso: "2026-09-19", date: "Sat 19 Sep", city: "Rome", country: "Italy",
    kind: "open", title: "Open",
    summary: "Nothing booked. Rain is a real possibility — 64%.",
    high: 80, low: 64, rain: 0.64,
  },
  {
    img: "rome-colosseum",
    n: 4, iso: "2026-09-20", date: "Sun 20 Sep", city: "Rome", country: "Italy",
    kind: "plan", title: "Colosseum — standard entry",
    summary: "Standard timed entry: Colosseum + Roman Forum + Palatine.",
    high: 79, low: 62, rain: 0.36,
    notes: [
      "The 30-day guided-tour window (21 Aug) came and went without getting one.",
      "Fall back to standard entry from coopculture.it — the official seller. Timed slots, far more inventory than the tours.",
      "Returned tickets reappear, so check availability more than once rather than waiting on a single date.",
      "Pick a slot and arrive early.",
    ],
  },
  {
    img: "rome-pantheon",
    n: 5, iso: "2026-09-21", date: "Mon 21 Sep", city: "Rome", country: "Italy",
    kind: "open", title: "Open", summary: "Nothing booked. Last full day in Rome.",
    high: 79, low: 62, rain: 0.36,
  },
  {
    img: "venice-canal",
    n: 6, iso: "2026-09-22", date: "Tue 22 Sep", city: "Rome → Venice", country: "Italy",
    kind: "travel", title: "Rome → Venice",
    summary: "Half travel day, ~5 hours door to door. The train is booked and seated; the water leg is not.",
    high: 78, low: 62, rain: 0.45,
    timeline: [
      { t: "9:40 AM", what: "Taxi to the station", detail: "Apartment → Roma Termini · ~15 min. Checkout is 10:00 AM — leave by 9:40 to keep the full 40-minute buffer at Termini." },
      { t: "10:35 AM", what: "Frecciarossa 9416", detail: "Roma Termini → Venezia S. Lucia · arrives 2:34 PM · 3h 59m · PNR TK2N7N · Coach 5, seats 11A Brandon / 11B Tatiana. Scan the barcode at the gate." },
      { t: "2:34 PM", what: "Arrive Venice", detail: "Get off at SANTA LUCIA, not Mestre. Mestre is the stop before and it is on the mainland." },
      { t: "~2:50 PM", what: "Onto the water", detail: "Private water taxi from the rank right outside S. Lucia — walk up and negotiate, ~25 min. No need to pre-book. Cheaper alternative: vaporetto Line 2 (faster than Line 1) to Santa Maria del Giglio, then ~5 min walk. With three weeks of luggage, take the private boat." },
      { t: "~3:20 PM", what: "Check in", detail: "Duodo Palace, Calle Minelli 1887–1888, San Marco. Evening free." },
    ],
    checklist: ["Ticket barcodes downloaded offline", "Apartment key returned / lockbox reset", "Chargers, adapters, passports", "Nothing left in the safe"],
  },
  {
    img: "venice-gondola",
    n: 7, iso: "2026-09-23", date: "Wed 23 Sep", city: "Venice", country: "Italy",
    kind: "plan", title: "Dinner — Al Vecio Forno, 7:30 PM",
    summary: "Party of 2, under 'Payne'. Daytime open.",
    high: 71, low: 59, rain: 0.64,
    notes: [
      "NO written confirmation was ever issued. Call to reconfirm a day or two ahead.",
      "Address and phone still need filling in — do it before you need them.",
      "Also today: 4:00 PM is the last moment to cancel tomorrow's cooking class.",
    ],
  },
  {
    img: "venice-canal",
    n: 8, iso: "2026-09-24", date: "Thu 24 Sep", city: "Venice", country: "Italy",
    kind: "plan", title: "Cooking class — pasta & tiramisu, 4:00 PM",
    summary: "Three hours, 2 adults, in English. You eat what you cook with wine, limoncello and coffee — treat it as dinner.",
    high: 70, low: 58, rain: 0.45,
    timeline: [
      { t: "3:50 PM", what: "BE THERE", detail: "Arrive 3:50 or the slot is forfeit." },
      { t: "4:00 PM", what: "Class starts", detail: "Taverna San Trovaso · Calle Contarini Corfù 1016, 30123 Venezia (Dorsoduro) — over the Accademia bridge, ~15 min walk from the hotel." },
    ],
    notes: [
      "GetYourGuide GYGN6BYFG5ZX · PIN q2f4T@wD. Tickets live in the GetYourGuide app — download before you fly.",
      "Provider: Cooking Italy, +39 377 341 8113. Tell them about allergies or food restrictions ahead of time.",
    ],
  },
  {
    img: "como-lake",
    n: 9, iso: "2026-09-25", date: "Fri 25 Sep", city: "Venice → Lake Como", country: "Italy",
    kind: "travel", title: "Venice → Lake Como",
    summary: "Two trains on one booking, then a car up the west shore. ~5 hours door to door.",
    high: 71, low: 57, rain: 0.45,
    timeline: [
      { t: "9:30 AM", what: "Vaporetto to the station", detail: "Hotel → Venezia S. Lucia · ACTV Line 2 via Rialto · ~40 min. Leave about 1h 15m before the train. Buy tickets the night before." },
      { t: "10:48 AM", what: "Frecciarossa 9724", detail: "Venezia S. Lucia → Milano Centrale · arrives 1:15 PM · 2h 27m · PNR TK9PWN · Coach 5, seats 9B Brandon / 9A Tatiana." },
      { t: "1:43 PM", what: "Regionale 25520", detail: "Milano Centrale → Como San Giovanni · arrives 2:23 PM · 40 min · 2nd class, no seat assignment. 28-minute transfer, protected because it is a single booking. NOTE: these two regional tickets are NOT in Apple Wallet — carry the per-passenger PDFs or read the codes to the conductor." },
      { t: "~2:40 PM", what: "Car up the shore", detail: "Como S. Giovanni → Via Regina 25, Griante · ~40 min. No train serves the west shore. Lake Como Transfers gave a quote but nothing is booked — the taxi rank outside the station always has one. Nothing downstream depends on it; check-in is self-service at 3pm." },
      { t: "3:00 PM", what: "Check in", detail: "Self check-in, lockbox. Have the code saved offline before you leave Venice." },
    ],
    checklist: ["Settle any hotel extras at Duodo Palace", "Lockbox code saved offline", "Vaporetto tickets bought the night before", "Regional-leg PDFs on the phone"],
  },
  {
    img: "como-lake",
    n: 10, iso: "2026-09-26", date: "Sat 26 Sep", city: "Lake Como", country: "Italy",
    kind: "open", title: "Open",
    summary: "Nothing booked. Worth walking down to Tremezzo to find tomorrow's boat dock while it is light.",
    high: 68, low: 58, rain: 0.55,
  },
  {
    img: "como-lake",
    n: 11, iso: "2026-09-27", date: "Sun 27 Sep", city: "Lake Como", country: "Italy",
    kind: "plan", title: "Boat rental, 11:00 AM – 3:00 PM",
    summary: "Motorboat 'Bellagio', four hours, from Tremezzo.",
    high: 69, low: 58, rain: 0.55,
    timeline: [
      { t: "10:45 AM", what: "Arrive at the dock", detail: "Be early — late arrival eats into your four hours. Tremezzo is ~10 min walk south along the shore from Griante. Parking near the dock is genuinely difficult in season, so walk." },
      { t: "11:00 AM", what: "Depart", detail: "Nautic Planet #2863 · back at 3:00 PM. Bring valid photo ID for both of you." },
    ],
    notes: ["Pack tonight. Tomorrow is the longest day of the trip and the car comes at 07:00."],
  },
  {
    img: "swiss-lucerne",
    n: 12, iso: "2026-09-28", date: "Mon 28 Sep", city: "Lake Como → Interlaken", country: "Italy → Switzerland",
    kind: "travel", title: "THE LONG DAY — four legs, ~10 hours",
    summary: "Car into Switzerland, then the Gotthard Panorama Express: scenic train, lake steamer, panoramic train. Everything keys off the 07:00 car.",
    high: 71, low: 57, rain: 0.27,
    critical: "Miss the 09:18 from Lugano and the whole chain falls apart, because the steamer runs once. Set an alarm for 06:00 and pack the night before.",
    timeline: [
      { t: "7:00 AM", what: "Car across the border", detail: "Pick-up 07:00 SHARP at Via Regina 25, Griante → Lugano Stazione FFS · ~1h–1h20 · Mercedes E-Class · Lake Como Transfers, Jenny +39 349 3431906 · ref X7XZW8VIUV. Ask for the MENAGGIO–PORLEZZA route, not Como–Chiasso — weekday commuter queues. Passports out at the border." },
      { t: "~8:20 AM", what: "Arrive Lugano", detail: "About an hour of slack against the bag deadline." },
      { t: "9:08 AM", what: "BAGS DUE", detail: "Drop bags at the Lugano departure track at least 10 min before departure. 23 kg per piece. NO ACCESS EN ROUTE — keep passports, meds and chargers on you. Collect at Luzern, Bahnhofquai Pier 1." },
      { t: "9:18 AM", what: "Gotthard Panorama Express", detail: "Lugano → Flüelen · arrives 11:35 AM · 2h 17m · train 3092 · reservation 421839-1 · Carriage 14, seats 71 & 72, 1st-class panorama car. Show: Swiss Pass + class upgrade + passport." },
      { t: "12:00 PM", what: "Lake Lucerne steamer", detail: "Flüelen → Luzern · arrives 2:47 PM · 2h 47m · open seating, 1st-class deck. Lunch served on board — table reservation recommended at lakelucerne.ch/tischreservation." },
      { t: "2:47 PM", what: "Collect bags at Luzern", detail: "Bahnhofquai Pier 1, where the steamer docks." },
      { t: "~3:06 PM", what: "Luzern–Interlaken Express", detail: "→ Interlaken Ost · arrives ~5:00 PM · ~2 h · no reservation, open seating, runs about hourly. Turn up and go." },
      { t: "~5:15 PM", what: "Walk to the flat", detail: "Höheweg 2 — about 10 minutes from Interlaken Ost. Check-in from 4:00 PM." },
    ],
    notes: ["The Swiss Travel Pass starts today and runs to 4 Oct, 5:00 AM."],
    checklist: ["Alarm set for 06:00", "Bags packed the night before", "Passports ON YOU, not in the transferred bag", "Meds, chargers, snacks in the day bag", "Lockbox code reset / key returned"],
  },
  {
    img: "interlaken-valley",
    n: 13, iso: "2026-09-29", date: "Tue 29 Sep", city: "Interlaken", country: "Switzerland",
    kind: "open", title: "Open — weather picks",
    summary: "First of four open days. Check the webcams the night before and decide over breakfast.",
    high: 66, low: 51, rain: 0.36, excursionDay: true,
  },
  {
    img: "swiss-first",
    n: 14, iso: "2026-09-30", date: "Wed 30 Sep", city: "Interlaken", country: "Switzerland",
    kind: "open", title: "Open — weather picks", summary: "Second of four open days.",
    high: 66, low: 52, rain: 0.55, excursionDay: true,
  },
  {
    img: "swiss-jungfrau",
    n: 15, iso: "2026-10-01", date: "Thu 1 Oct", city: "Interlaken", country: "Switzerland",
    kind: "open", title: "Open — weather picks", summary: "Third of four open days.",
    high: 64, low: 52, rain: 0.64, excursionDay: true,
  },
  {
    img: "swiss-oeschinen",
    n: 16, iso: "2026-10-02", date: "Fri 2 Oct", city: "Interlaken", country: "Switzerland",
    kind: "open", title: "Open — weather picks", summary: "Last open day in Switzerland.",
    high: 65, low: 51, rain: 0.64, excursionDay: true,
  },
  {
    img: "paris-eiffel",
    n: 17, iso: "2026-10-03", date: "Sat 3 Oct", city: "Interlaken → Paris", country: "Switzerland → France",
    kind: "travel", title: "Interlaken → Paris",
    summary: "Two separate tickets. The buffer at Basel is the thing to protect.",
    high: 63, low: 50, rain: 0.82,
    critical: "The Swiss leg and the TGV are unconnected tickets, so a late Swiss train is your problem, not the railway's. If an earlier Interlaken departure is sitting there, take it.",
    timeline: [
      { t: "9:15 AM", what: "Walk to the station", detail: "Höheweg 2 → Interlaken Ost · ~10 min. Checkout 10:00 AM." },
      { t: "~9:30 AM", what: "Swiss InterCity", detail: "Interlaken Ost → Basel SBB via Bern · ~2 h · arrives ~11:30. Turn up and go on the Swiss Pass — day 6, the last day it is valid." },
      { t: "11:30 AM", what: "~1 hour at Basel", detail: "This buffer matters. Grab lunch, find the platform early." },
      { t: "12:34 PM", what: "TGV Lyria", detail: "Basel SBB → Paris Gare de Lyon · arrives 3:38 PM · 3h 04m · order 151490866652 · Wagon 16, seats 662 Brandon / 663 Tatiana, upper deck · 2nd class, Semi Flex." },
      { t: "~3:50 PM", what: "Taxi to the hotel", detail: "Gare de Lyon → 1 Rue Augereau, 7th · ~25 min, across the Seine." },
      { t: "~4:15 PM", what: "Check in", detail: "Hotel de Londres Eiffel. Evening free." },
    ],
    checklist: ["Spend or keep leftover francs — euros will not work here", "Flat cleaned, code reset, keys returned", "TGV ticket saved offline", "Swiss Pass expires 4 Oct 5:00 AM — today is the last use"],
  },
  {
    img: "paris-eiffel",
    n: 18, iso: "2026-10-04", date: "Sun 4 Oct", city: "Paris", country: "France",
    kind: "open", title: "Open", summary: "Nothing booked. Also today: you move to the Eiffel-view room on the 6th floor.",
    high: 64, low: 47, rain: 0.27,
  },
  {
    img: "paris-eiffel",
    n: 19, iso: "2026-10-05", date: "Mon 5 Oct", city: "Paris", country: "France",
    kind: "open", title: "Open", summary: "Nothing booked.",
    high: 64, low: 50, rain: 0.36,
  },
  {
    img: "paris-eiffel",
    n: 20, iso: "2026-10-06", date: "Tue 6 Oct", city: "Paris", country: "France",
    kind: "plan", title: "Disneyland Paris",
    summary: "Both parks, one day. Premier Access makes that realistic. Out the door by 7:45 AM.",
    high: 64, low: 50, rain: 0.45,
    critical: "The confirmation email will NOT get you in. QR codes for tickets AND Premier Access live in the Disneyland Paris app under 'My Tickets & Passes'. Load them offline the night before and bring photo ID for both of you.",
    timeline: [
      { t: "7:45 AM", what: "Walk, then Metro 8", detail: "1 Rue Augereau → École Militaire (~8 min) → Opéra (~12 min, 7 stops)." },
      { t: "~8:10 AM", what: "Transfer on foot", detail: "Opéra → Auber through the underground complex · 5–8 min." },
      { t: "~8:20 AM", what: "RER A east", detail: "Board a train showing MARNE-LA-VALLÉE–CHESSY — not Boissy-Saint-Léger, which is the other branch. ~40 min. For a seat, board at Charles de Gaulle–Étoile instead — it is the first central stop." },
      { t: "~9:05 AM", what: "Arrive", detail: "Chessy is the terminus — you cannot overshoot it. Under 5 min walk to the gates. Park opening is typically 9:30; confirm in the app the night before." },
      { t: "~12:20 AM", what: "Last trains back", detail: "Roughly 12:20 AM from Chessy, so the evening show at park close is comfortably doable. If exhausted, an Uber back to the 7th is a defensible splurge after 12 hours on your feet." },
    ],
    notes: ["Both phones fully charged — the app is your ticket all day."],
  },
  {
    img: "paris-eiffel",
    n: 21, iso: "2026-10-07", date: "Wed 7 Oct", city: "Paris", country: "France",
    kind: "plan", title: "Dinner — Café de l'Homme, 8:00 PM",
    summary: "Party of 2, indoor, standard seating. Daytime still open.",
    high: 63, low: 50, rain: 0.45,
    notes: [
      "17 Place du Trocadéro, 75016 — in the Palais de Chaillot, straight across the Seine from the Eiffel Tower.",
      "Booked via OpenTable, status Experience confirmed. No prepayment — pay at the restaurant.",
      "Change or cancel under 'Manage reservation' in the OpenTable app.",
    ],
  },
  {
    img: "paris-eiffel",
    n: 22, iso: "2026-10-08", date: "Thu 8 Oct", city: "Paris", country: "France",
    kind: "plan", title: "Last full day — and book the airport taxi",
    summary: "Open daytime, but one job today.",
    high: 65, low: 50, rain: 0.18,
    critical: "Ask Londres Eiffel reception TODAY to order a taxi for 6:15–6:30 AM tomorrow. Free to arrange, and it removes the only real risk of the morning — hailing in the 7th at 6:30 AM is unreliable and app rides cancel.",
    checklist: ["Taxi ordered with reception for 6:15–6:30 AM", "Hotel bill settled", "Bags under 23 kg each", "No liquids over 100 ml in carry-on", "VAT refund forms, if any"],
  },
  {
    img: "paris-eiffel",
    n: 23, iso: "2026-10-09", date: "Fri 9 Oct", city: "Paris → home", country: "France → USA",
    kind: "travel", title: "Fly home",
    summary: "Nonstop. Wheels down in Salt Lake the same afternoon.",
    high: 65, low: 48, rain: 0.27,
    timeline: [
      { t: "~6:30 AM", what: "Car to CDG", detail: "1 Rue Augereau → Paris CDG · 45–60 min · Paris runs a regulated flat fare from the Left Bank to CDG. Confirm it as you get in." },
      { t: "~7:30 AM", what: "Check in, Terminal 2E", detail: "Bags dropped, security, passport control out of Schengen." },
      { t: "10:25 AM", what: "DL 221 departs", detail: "Paris CDG → Salt Lake City · nonstop · 10h 54m · A330-900neo · Brandon seat 46H · conf. GKS49A." },
      { t: "1:19 PM", what: "Land Salt Lake City", detail: "Same day. Two free checked bags each." },
    ],
    notes: ["Three and a half to four hours before an international departure. It feels early. CDG on a Friday morning does not reward optimism."],
    checklist: ["Passports and boarding passes on phones", "Hotel bill settled", "Safe emptied", "Chargers and adapters", "Leftover euros spent or kept"],
  },
];
